// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Base: typeof import('./api/base.ts')['default'];
    HelloWorld: typeof import('./components/HelloWorld.vue')['default'];
    LoginButton: typeof import('./components/LoginButton.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Test: typeof import('./api/test.ts')['default'];
    Test2: typeof import('./api/test2.ts')['default'];
    TSXDemo: typeof import('./components/TSXDemo/index.tsx')['default'];
  }
}

export {};
